### ISSUE TITLE
Can run Hutoma

### ISSUE THREAD

**Issue by aermike** [hutomadotAI/Hutoma-Conversational-AI-Platform#22]
I follow the instructiuns to install hutoma
At launch ./lanch.sh or .\launch_local.sh receive that error
 Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version.
Please help

**Comment by ghost** [comment]
Hi, that seems an issue with your version of docker/docker-compose not supporting version 3 of the docker-compose file. Please make sure you have up to date versions of both the docker engine and docker-compose. You can see the compatibility list at: https://docs.docker.com/compose/compose-file.
Thanks.

**Comment by aermike** [comment]
Thank you.
